lockfale/OSINT-Framework

public/arf.json

Hey there,
This adds my newly released Twitter OSINT tool [Birdwatcher](http://michenriksen.com/blog/birdwatcher-twitter-osint-framework/) under `Social Networks` -> `Twitter` -> `Analytics`.
I gave the new node the highest unused ID; I hope that is the correct way to do it.
Thanks for an awesome resource!

Add Birdwatcher

---

public/arf.json

This adds a link to [StackShare](https://stackshare.io/) which I think is a pretty nifty resource for finding out what technologies and tools an organization is using. Here's some example reports:
* [Airbnb](https://stackshare.io/airbnb/airbnb)
* [Spotify](https://stackshare.io/spotify/spotify)
* [GitHub](https://stackshare.io/github/github)

Add StackShare under Domain Name > Analytics

---

public/arf.json

* CloudFail (T) - Utilize misconfigured DNS and old database records to find hidden IP's behind the CloudFlare network
* OpenRailwayMap - OpenRailwayMap (previously called "Bahnkarte") is a detailed online map of the world's railway infrastructure, built on OpenStreetMap data.

Added CloudFail and OpenRailwayMap

---

public/arf.json

raven is a Linkedin information gathering tool that can be used by pentesters to gather information about an organization employees using Linkedin.

added raven (T) to "Other Social Networks"

---

public/arf.json

* "GOVDATA" federal german open data platform, published by Finanzbehörde Hamburg (Hamburg Finance Dept.)
* Open Data Portal München, published by the Munich municipality
* Deutsche Bahn Open-Data-Portal, published by Deutsche Bahn AG

Added 3 german open data providers

---

public/arf.json

Onion Investigator "This site was created out of curisoty, how easy would it be to create a shodan like website and service for .onions, turns out it is pretty easy."

Added Onion Investigator to Darkweb - Discovery

---

public/arf.json

certgraph - An open source intelligence tool to crawl the graph of certificate Alternate Names

Added certgraph

---

public/arf.json

GlobalFileSearch.net does not exist.
GlobalFileSearch.com does exist.

Fix GlobalFileSearch link

---

public/arf.json

Add [MailDB.io](https://maildb.io/).
>    Discover all contacts for any company on the web
>    First name, last name, job title, and phone number included, automatically and free of charge
Requires API key.
Allows searching by name and/or domain.
Returns email addresses, and a list of sources (web pages), with date stamp, of when each email address was retrieved from the source.
Sometimes also returns other interesting info, like name and job title.

Add MailDB.io

---

public/arf.json

Created a new entry 'IP Loggers' as a child of IP Address. 
Included 2 projects
1. Ki.tc, which includes several CLI sub-projects but the prominent one is the 'url shortener' which features IP logging and Browser Fingerprinting given a link. [CLI]
2. Grabify, which includes the ability to select the desired link domain from a comprehensive list. [Web-Based]

IP loggers in IP Address

---

public/arf.json

skresolver.com is a parked domain
I haven't tested skypeipresolver.net; however it appears to be a suitable replacement.

Update Skype Resolver link

---

public/arf.json

Added a couple tools to the Threat Intelligence -> IOC Tools section:
* [iocextract](https://github.com/InQuest/python-iocextract) - Advanced Indicator of Compromise extractor.
* [ThreatIngestor](https://github.com/InQuest/ThreatIngestor) - Threat intel automation tool.
Let me know if you'd like these moved to a different section or anything.

Add iocextract and ThreatIngestor

---

public/arf.json

Repo moved from bitbucket to git:

updated url of Recon-ng

---

public/arf.json

Current link to DNSstuff is incorrect and send us to tools reviews page (https://www.dnsstuff.com/tools). I suggest to replace this link with link to https://tools.dnsstuff.com/ which is tools homepage.

improvement: correct dnsstuff whois lookup tool link

---

public/arf.json

Markmonitor whois lookup tool moved from https://www.markmonitor.com/cgi-bin/affsearch.cgi? to https://domains.markmonitor.com/whois/charlescawleysucks.com

fix: correct markmonitor whois lookup link

---

public/arf.json

Whoismind (http://www.whoismind.com/) redirects to Whois AMPed (https://whoisamped.com/), so i suggest to replace the link and the service title.

improvement: replace Whoismind with Whois AMPed

---

public/arf.json

I could not find any whois infomation about domain on dnsdumpster (https://dnsdumpster.com/), so i suggest to remove it from whois lookup tools list.

improvement: removed DNSdumpster from whois

---

public/arf.json

1. Removed duplicated link to CertDB in the same section
2. Replaced CertDB with Spyse, since CertDB (https://certdb.com/) is now part of the Spyse service (https://spyse.com/search/certificate)

improvement: removed duplicated CertDB and update URL

---

public/arf.json

"Daily DNS Changes" service (http://www.dailychanges.com/) become a part of DomainTools service and have no any direct whois records search anymore.

improvement: removed Daily DNS Changes from domains whois tools list

---

public/arf.json

ipintel.io seems to be dead.
It has not been working since at least September 3:

improvement: removed ipintel.io from ip geo list

---

public/arf.json

domainhistory.net seems to be inactive for a long time, so i suggest to remove it from domain whois lookup services list.
According to webarchive (http://web.archive.org/web/2018*/domainhistory.net) it haven't been seen from more then one year, so i think it is not site temporary unavailability problem.

improvement: removed domainhistory.net from whois

---

public/arf.json

DNStable (https://dnstable.com/) service does not provides whois information about any domains's.

improvement: remove DNStable from domain whois

---

public/arf.json

What is AbuseIPDB?
AbuseIPDB is a project dedicated to helping combat the spread of hackers, spammers, and abusive activity on the internet.
Our mission is to help make Web safer by providing a central blacklist for webmasters, system administrators, and other interested parties to report and find IP addresses that have been associated with malicious activity online.
You can report an IP address associated with malicious activity, or check to see if an IP address has been reported, by using the search box above.
Power user? Consider registering an account to gain access to our powerful, free API for both reporting and checking the report status of IP addresses. We also support integration with Fail2Ban for automated reporting of abusive IPs.

adding abuseipdb.com record

---

public/arf.json

Domainsdb.info (https://domainsdb.info/) does not provide any whois information. 
> Registered domains search checks the lists of registered domains for names containing particular words/phrases/numbers or symbols. Technically it's just a GUI interface for domains-index.com database containing more than 260M of registered domains and 1000+ TLDS including newGTLDs. It's free to use and could be helpful domains/marketing research tool.

improvement: removed Domainsdb.info from whois tools

---

public/arf.json

The GitHub for Bluto should be https://github.com/darryllane/Bluto
Addressing issue #214

Fixing the correct GitHub repo URL for Bluto

---

public/arf.json

See the following 2 points for how namesdir.com can help when doing OSINT:
-- Given a name (first name or last name), namesdir can help suggest usernames that someone with that name could likely use. So if you have been able to OSINT a name to a platform, namesdir can provide good username suggestions. To see these username suggestions, go to namesdir.com, search for a name, click on the name and scroll down to "Typos & Misspells"
-- Imagine this, you're on an OSINT hunt, you need to determine the full name of your OSINT target person, you come across an image with a name. You have a good hunch that this is the name of your target person. However, the image is blurred out or some characters of the name in the image are unreadable. You notice you are only able to read the first name …

Include namesdir.com url in Username Search Engines folder

---

public/arf.json

Namechk (T) has not been updated for 4 years and the [github page](https://github.com/HA71/Namechk) says the tool does not work properly. 
I might create another PR if this gets merged for adding [Sherlock](https://github.com/sherlock-project/sherlock)

deleted Namechk(T) as deprecated

---

public/arf.json

A missing comma after an array element caused error while parsing JSON.
Problematic code:
_Missing comma at line 4193_
https://github.com/lockfale/OSINT-Framework/blob/80a6eb037f98ccc549ee595c62ea1b214180bf38/public/arf.json#L4189-L4195

fix: missing comma after array element

---

public/arf.json

URL for gitleaks: https://gitleaks.com is not valid, replace with https://github.com/zricethezav/gitleaks

Update URL for gitleaks (code search)

---

public/arf.json

Freenet is free software which lets you anonymously share files, browse and publish "freesites" (web sites accessible only through Freenet) and chat on forums, without fear of censorship. Freenet is decentralised to make it less vulnerable to attack, and if used in "darknet" mode, where users only connect to their friends, is very difficult to detect.

update(arf.json): Added Freenet Project

---

public/arf.json

This category title right now does not indicate that some tools nested under it can be used based on a MAC address (i.e. WiGLE), so it would be useful to make the name more broad. Maybe "IP & MAC Address" is not the best fit, but it's the first thing that comes to mind.

Update arf.json category from "IP Address" to "IP & MAC Address".

---

public/arf.json

GeoChirp (geochirp.com) under "Social Networks," "Twitter," "Location / Mapping" returns an otherwise blank website with the header "Website Disabled."

Remove GeoChirp

---

public/arf.json

I deleted Corporate Email Formats from OSINT Framework > Email Address > Common Email Formats > Corporate Email Formats. This website returned a 404 error - Page Not Found

Update arf.json - Deleted Not-Found Page

---

public/arf.json

The website Profile engine (https://www.afternic.com/forsale/PROFILEENGINE.COM?traffic_type=TDFS&traffic_id=GoDaddy_DLS) is outdated, apparently it is not up anymore.

Took away an outdated website, "Profile Engine"

---

public/arf.json

Reverting #123 because maildb.io now leads to a broken link.

Remove maildb.io

---

public/arf.json

Remove Pastebin Trends, the URL http://pastebin.com/trends does no longer work.

Remove Pastebin Trends

---

public/arf.json

did not remove the tool, as there is benefit in having both alternatives

added the web-hosted version of whatsmyname

---

public/arf.json

This simple PR adds Analyst Research Tools, analystresearchtools.com in the "OSINT Automation" folder

Add Analyst Research Tools in the "OSINT Automation" folder 

---

public/arf.json

Mailshunt.com has been compromised and now redirects users to various scam sites that prompt them to call a fake support number. Attached is a screenshot of one such redirect.

Remove Compromised URL from Email Search

---

public/arf.json

Here's a complete list of removals/changes with reasoning, broken down by subsection:
Social Networks > Facebook > Search
findmyfbid.com - domain has no A record
FB People Directory - returns an error saying "blocked by our security systems" netbootcamp.org - domain has no A record
searchisback.com - site is inaccessible, site functionality stopped in 2019-ish socialsearching.info - site is inaccessible since 2018 (wayback machine) Facebook Live Map - functionality removed from FB in 2019
Social Networks > Facebook > Analytics
stalkscan.com - domain has no A record
Social Networks > Twitter > Search
Twitter Name Search - functionality removed from Twitter Twitter User Directory - functionality removed from Twitter Twitter Search for Live Streaming Video - functionality removed from …

Update arf.json to remove dead links under Social Networks

---

public/arf.json

Adds the EZR OSINT Sidebar (free chrome extension) to the "Documentation / Evidence Capture" folder.

Add EZR OSINT Sidebar

---

public/arf.json

Proposal to add Netlas.io, a search engine and web crawler similar to Shodan. Given the number of tools and the amount of data that Netlas offers, it can be useful in many use cases.

Add Netlas.io search engine
