arf.js, arf.json, index.html
Initial site files… Lots to fix…
=> Site files

public/arf.json
Added to the "Maps" folder:
https://opensignal.com ("Insight into the coverage and performance of Mobile Operators worldwide")
http://www.antennasearch.com ("Detailed information on over 1.9 Million Towers and Antennas in the US")
=> More Maps-Tools

public/arf.json
=> URL Update (Jeffrey's Exif Viewer)

public/arf.json
added drone Links (Maps, Footage) into the maps category
=> Links added

public/arf.json
Added Overview (open source document mining platform) to Tools.
=> Link added

public/arf.json
Removed Leakedsource (down/busted) and added Vigilante.pw (Breach database)
Added botbot.me (IRC logs) and netsplit.de (IRC Search)
=> Link updates

public/arf.json
=> url update

public/arf.json
added HoneyDB and Mimir (Issue Add HoneyDB + CLI. #44)
=> Added HoneyDB

public/arf.json
Reference to this issue :) 
https://github.com/lockfale/OSINT-Framework/issues/47
=> Add Belati to the list

public/arf.json
Full Page Screen Capture Chrome Extension and Greenshot (Screenshot Tool for Windows)
=> Added Screenshot Tools

public/arf.json
who.com.co - FREE PUBLIC DATA FINDER
=> Added who.com.co

public/arf.json
=> Added analyzeid.com

public/arf.json
Domain is for sale, presumably no longer available?
=> Remove PDF Geni

public/arf.json
IntRec-Pack - Intelligence and Reconnaissance Package/Bundle installer.
=> Added IntRec-Pack

public/arf.json
A browser extension for navigating burgeoning Twitter conversations
=> Added Treeverse

public/arf.json
OSINT-SPY performs OSINT scan on email/domain/ip_address/organization
=> Added OSINT-SPY, fixed duplicate id

public/arf.json
=> Added License Plate Search

public/arf.json
iptrackeronline.com - "IP Address tools, email header analyzer"
=> Added iptrackeronline to IP Address > Geolocation

public/arf.json
Added Reverse Phone Search (USPhonebook.com) to Telephone Numbers
=> Added usphonebook.com

public/arf.json
From a conversation on Twitter.
=> Added DNS Dumpster

README.md
"my" -> "may" in "..sites included my require registration.."
Noticed this while reading through the OSINT Framework files. 
Thanks for the framework!
=> Fix minor typo - README.md

public/arf.json
DeepL trains artificial intelligence to understand and translate texts.
=> Added ID 1291 - DeepL Translator

public/arf.json
[1317] [Marine Records] OpenSeaMap - The free nautical chart - http://www.openseamap.org
[1318] [Railway Records] OpenRailwayMap - https://www.openrailwaymap.org/
[1319] [Wireless Network Info] OpenCellid Database of Cell Towers - https://opencellid.org/
Next Available ID: 1320
=> Updated: Marine Records, Railway Records, Wireless

public/arf.json
[1320] [Archives] [Web] [Waybackpack - Download the entire Wayback Machine archive for a given URL]
next available ID: 1321
=> Added Waybackpack (T)

public/arf.json
[1322] [Transportation] [Air Traffic Records] [ADS-B Exchange - World's largest co-op of unfiltered flight data]
next available ID: 1323
=> Added ADS-B Exchange

public/arf.json
line 3800 id: 531 - changed https://inteltechniques.com/intel/osint/telephone.html to https://inteltechniques.com/osint/telephone.html
=> updated arf.json

public/arf.json
[1333] [Domains] [Subdomains] [FindSubDomains]
[1334] [Domains] [Tools] [Hunting-Newly-Registered-Domains]
=> Added FindSubDomains, Hunting-Newly-Registered-Domains

public/arf.json
[1344] [Username] [Search Engines] [Namechk (T)]
Namech_k.sh Osint tool based on namechk.com for checking usernames on more than 100 websites, forums and social networks.
=> Added Osint tool based on namechk.com

public/arf.json
[1345] [Videos] [Analyze/Record]
Renders graph of related YouTube videos.
=> Added yasiv-youtube (Graph of related videos)

public/arf.json
Omnibus is an open source Python application for OSINT collection and artifact management. It provides an interaction CLI application where users can collect OSINT data from public sources on artifacts such as IP addresses, domain names, email addresses, usernames, file hashes, and Bitcoin addresses.
- https://github.com/InQuest/Omnibus
=> Add Omnibus to OSINT automation Tools section

public/arf.json
Incrementing next available node.
=> Adding SANS SEC487 to training

public/arf.json
[1349] [Docs] [Documents] [Paste Sites] [Pastebin OSINT Harvester (T)]
Multithreaded pastebin scraper, scrapes to mysql database, then reads pastes for noteworthy information.
=> Added Pastebin OSINT Harvester (T)

public/arf.json
[1350] [Dark Web] Added IACA Dark Web Investigation Support - Provided by International Anti Crime Academy
=> Added IACA Dark Web Investigation Support

public/arf.json
Add Pulsedive, a new threat intelligence platform, to the Threat Intelligence category.
=> Add Pulsedive

public/arf.json
Search for email address by domain.
=> Add Skymem

public/arf.json
Mr.Looquer IOC Feed is the 1st Dual Stack Threat Feed.
Mrlooquer has created the first threat feed focused on systems with dual stack. Since IPv6 protocol has begun to be part of malware and fraud communications, It is necessary to detect and mitigate the threats in both protocols (IPv4 and IPv6).
=> Adding Mr.Looquer IOC Feed

public/arf.json
https://emailrep.io/ added to Email Verification.
=> Email Verification added.

public/arf.json
Punk.sh was a continuation of punkspider
Both now no longer bring up tools
=> Clean up punkspider/punk.sh

public/arf.json
add ahrefs and topgainers to analytics, certdb to Certificate Search, aslookup to ipv4, port map to port dicovery
=> updated a few categories

public/arf.json
> This is an Internet-scale port scanner. It can scan the entire Internet in under 6 minutes, transmitting 10 million packets per second, from a single machine.
=> improvement: added masscan tool to "port discovery" section

public/arf.json
=> improvement: added "Requires registration" to Robtex whois lookup service

public/arf.json
tools > osint automation > threatpipes
=> adding threatpipes record

public/arf.json
Added these two websites under dating section as they as widely used dating websites these days.
=> Added Bumble and Hinge under Dating 

public/arf.json
Repo: https://github.com/owasp/D4N155
Wiki: https://owasp.org/www-project-d4n155/
=> :tada: Add OWASP D4N155 #179

public/arf.json
Removing Dronetheworld and TerraServer as they are 404, adding openinframap.
=> removing dronetheworld and TerraServer, adding openinframap

public/arf.json
Added to both 'Search' and 'Hosted Automated Analysis/Office Files' under 'Malicious File Analysis'. Side note, XecScan appears to be defunct.
=> Added InQuest Labs Maldoc Resources

public/arf.json
Removing websites that no longer exist or point to a different website
=> Removing websites that no longer exist

public/arf.json
New url in IP adresses / blacklist
=> Add ABUSEIPDB

public/arf.json
Add PimEyes face recognition search engine under image search in arf.json
https://pimeyes.com/en
=> Add PimEyes Search Engine under Image Search

public/arf.json
Add PimEyes face recognition search engine under image search in arf.json
https://pimeyes.com/en
=> Add PimEyes

public/arf.json
Tried to use this tool, requires registration and payment at the end to see results.
=> Been Verified requires registration and payment

public/arf.json
=> Add urlDNA

public/arf.json
Add sites:
1. IntelligenceX - https://intel.io - OSINT Automation
2. Zenodo - https://zenodo.org - Other Search
Move site to appropiate category:
- site: Shuriken
- move from: General Search
- move to: Meta Search
=> Add 2 sites, Move 1 site to another folder

public/arf.json
Added https://picarta.ai/, a website to identify photo locations. Worked reasonably well in my limited testing.
=> Added Picarta

public/arf.json
=> Added geolocation tool - Astrometry

public/arf.json
Free Cybercrime Intelligence Toolkit
=> Added Hudson Rock to Breached Data section

public/arf.json
add vulert.com to advisories section
=> add vulert to advisories section

public/arf.json
adds vulert, a open source dependencies scanner to tools section
=> adds vulert, a open source dependencies scanner to tools section

public/arf.json
Hello,
We are a new internet scanning and search platform for IPv4, Certificates and upcoming Open Buckets.
ODIN by Cyble - https://getodin.com
We are looking to add ourselves to four different places:
1. Discovery
2. Certificate Search
3. Host / Port Discovery
4. IPv4
Thank you!
=> Update arf.json with ODIN by Cyble - One Platform for All your Internet Searches

package-lock.json, public/arf.json
I have made a new directory 'AI Tools'. I have also added WormGPT-6 AI to this catagory. Unlike ChatGPT, WormGPT does not invoke ethical standards, legal considerations. This allows it to provide answers that can not be provided by ChatGPT.
=> Add AI Tools directory and WormGPT-6

public/arf.json
This is the best guide for opsec so far out there, it MUST be included in this OSINT Framework without a single doubt.
=> Adding the real "The Hitchhiker’s Guide to Online Anonymity" guide to OpSec section

public/arf.json
Added W Generator Website (https://app.wgen.io/) - useful website for generating comprehensive wordlists based on different parameters that can be customized. Wordlist is saved as .txt file.
=> Adding Wordlist Generator Website under Tools>Wordlist

public/arf.json
Adding skyfi directory of free satellite images (requires registration).
=> Adding skyfi - free satellite images

public/arf.json
it's a proclaimed privacy-friendly service providing `GPT-3.5 Turbo` `Claude 3 Haiku` `Llama 3 70B` `Mixtral 8x7B`.
[DuckDuckGo AI Chat](https://duckduckgo.com/aichat)
=> Update arf.json, add'DuckDuckGo AI Chat'

public/arf.json
Add Swisscows, Brave, and Stract to General Search folder
=> Update general search folder in arf.json
